development:
  adapter: postgresql
  database: sampleappdb
  username: postgres
  password: root123
  host: 127.0.0.1
test:
  adapter: postgresql
  database: sampleappdb
  username: postgres
  password: root123
  host: 127.0.0.1
production:
  adapter: postgresql
  database: sampleappdb
  username: postgres
  password: root123
  host: 127.0.0.1
 